### PR TITLE
fixed code

### PR DESCRIPTION
**Pull request by 1chiSensei**
added more useful comments and fixed the code

### CODE REVIEW

**Comment by 1chiSensei** [comment]
@Leref when will you

**Review by camden-git — CHANGES_REQUESTED** [review]
I wouldn't approve this, this has 
1. No code changes, just playing with code comments. 
2. Many of the code comments are useless 
3. There are so many code comments that people might as well just read readme.md. 

This in summary seems like a small tweak that is useless and adds minimal help to the end user.

**Comment by ZeffDebunked** [comment]
just no, the only thing that might be good is the `;` which are not needed anyway (but I recommend them)

**Comment by Leref** [comment]
It's fine how it is :)

**Pull request closed without merging**
